name: Validate JSON

on: [push, pull_request]

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          python -m pip install -r requirements.txt
      - name: Validate latest.json
        run: |
          python scripts/validate.py schemata/latest.schema.json latest.json
